site_name: Introduction to Data & Systems
nav:
    - Home: index.md
    - Chapters:
        - 'Introduction' : 'systems/0-intro.md'
        - 'Chapter 1: Version Control Systems' : 'systems/1-vcs.md'
    - About: about.md
copyright: "Â© 2019, Tom Gregory"
theme: cinder
extra_css:
  - "css/docs.css"
markdown_extensions:
    - abbr
    - toc:
        permalink: false
    - admonition
    - footnotes
    - smarty
    - pymdownx.mark
shortcuts:
    help: 191    # ?
    next: 39     # right arrow
    previous: 37 # left arrow
    search: 83   # s
